### ISSUE TITLE
Not a problem but a compliment

### ISSUE THREAD

**Issue by Arva354** [sunkanmii/Windows-10-Pro-Emulator#22]
Hey sunkanmii! I like this windows emulator but maybe you can do better by making everything interactive like blueedge's windows 11 emulator but this is a start at least that would pay off
this is mostly good 😄

**Comment by sunkanmii** [comment]
Thank you, @Arva354 
Checked it out and it's pretty good. :)

Taken note and would try and improve for future versions.
